### ISSUE TITLE
How to configure that the Monitor power off after 10 minutes and power on on touch?

### ISSUE THREAD

**Issue by blueicehaller** [jareware/chilipie-kiosk#115]
I would like to configure that the monitor is going to sleep when nobody using the system.
One Wakeup event is when anybody uses the touchscreen (Iiyama ProLite T2735MSC).
Is there a preferred way?

**Solution**
Open ```sudo raspi-config```, select ```7 Advanced Options - Configure advanced settings```
and enable ```A6 Screen Blanking - Enable/Disable screen blanking```

Edit ```~/.xsession``` and change the following (comment out two xset options and add two other)
```
# Set some useful X preferences
xset s off # don't activate screensaver
# xset -dpms # disable DPMS (Energy Star) features.
# xset s noblank # don't blank the video device
xset +dpms                 # enable DPMS (Energy Star) features
xset dpms 3600 0 0         # xset [dpms standby [ suspend [ off]]]
```

You can test using 20 instead of 3600 seconds.

Then ```sudo reboot```

Further Information: [xset manual page](https://www.x.org/archive/X11R7.5/doc/man/man1/xset.1.html)

<br>

**Previous written**
Is it possible to use the scripts in Home (which are used in [crontab](https://github.com/futurice/chilipie-kiosk/blob/master/home/crontab.example))?
```
~/display-off.sh
~/display-on.sh
```

Is blanking (```consoleblank```) or ```xscreensaver``` what I'm searching for?
https://www.raspberrypi.org/documentation/configuration/screensaver.md

And what is this?
https://www.raspberrypi.org/documentation/configuration/config-txt/video.md
hdmi_blanking

The ```hdmi_blanking``` command controls what happens when the operating system asks for the display to be put into standby mode, using DPMS, to save power. If this option is not set or set to 0, the HDMI output is blanked but not switched off. In order to mimic the behaviour of other computers, you can set the HDMI output to switch off as well by setting this option to 1: the attached display will go into a low power standby mode.

**On the Raspberry Pi 4, setting hdmi_blanking=1 will not cause the HDMI output to be switched off, since this feature has not yet been implemented.**

**Comment by codeclinic** [comment]
@blueicehaller Did you have to install xscreensaver? When I activate screen blanking via raspi-config I get the message "dpkg-query: no packages found matching xscreensaver".

**Comment by blueicehaller** [comment]
Yes I confirm that behavior.

**Comment by codeclinic** [comment]
So you did install xscreensaver?

**Comment by blueicehaller** [comment]
No I didn't because it's not necessary in my case.
Today I tested on a fresh install and I just had to comment out two xset options and then sudo reboot.
You can test the behavior using 20 seconds:
`xset dpms 20 0 0`

Offtopic: Fresh install was necessary on a new SD Card because my previous no longer started with kernel panic.

**Comment by bernardovalente** [comment]
@blueicehaller  I don't have `A6 Screen Blanking - Enable/Disable screen blanking` on advanced settings, any idea why? I just did a fresh install and for A6 is `A6 Pixel Doubling`.

**Comment by blueicehaller** [comment]
Which model?
I am now trying to update my Raspberry Pi (I already upgraded raspi-config and currenty `sudo apt update && sudo apt upgrade` is running) to see if the option disappears.
At the moment the option is still available.

https://www.raspberrypi.org/documentation/configuration/raspi-config.md

**Comment by bernardovalente** [comment]
3b+. It's working though, i just edited the .xsession file an installed xscreensaver. Thank you

**Comment by codeclinic** [comment]
> 
> 
> 3b+. It's working though, i just edited the .xsession file an installed xscreensaver. Thank you

@bernardovalente  Please share your edited .xsession file. I also have the 3b+ and cannot get it working.

**Comment by bernardovalente** [comment]
sorry for the delay:

`
xset +dpms
xset dpms 20 0 0`

**Comment by blueicehaller** [comment]
Currently I don't have access to my Raspberries.
Can you please check if the Monitor power on if you call `~/display-on.sh`?
If yes maybe you can call it from the [gpio-watch](https://github.com/larsks/gpio-watch)?

**Comment by bernardovalente** [comment]
yes i can call `~/display-on.sh` but i'm not really sure how to auto run the `gpio-watch -e rising 4` command on start uo or how to use a symlink, sorry i'm kind of new on raspberrys...

**Comment by blueicehaller** [comment]
Did you meanwhile try to create an symlink `sudo ln -s /etc/gpio-scripts/4 ~/display-on.sh` ?
