### ISSUE TITLE
Raspi-Config randomily shows up

### ISSUE THREAD

**Issue by igloo15** [jareware/chilipie-kiosk#125]
I am not sure when it happens but I think it happens after the crontab restart. I currently have it setup so that it refreshes every hours, turns display off at 3:10am and restarts at 3am everyday. This is all from the crontab. I noticed that every morning when I wake up the raspi-config is up for some reason. I am not entirely sure what is causing it. 

I also noticed that if I have a keyboard plugged in to the raspiberry pi 3B then the raspi-config does not come up. This happened after one night leaving the keyboard plugged in and coming back to see it not on raspi-config in the morning. I tested this a couple more times and noticed as long as keyboard remains plugged in whatever happens during the night does not trigger raspi-config coming up. As soon as I unplug the keyboard though the next day when I wake up it will be showing the raspi-config screen.

**Comment by SnorreSelmer** [comment]
Have you activated "auto-off/on monitors" via DKMS? I tried that on my setup, but when the machine did the auto-on in the morning, it defaulted to "shell 2" which is raspi-config. This happened 100% for me.

**Comment by igloo15** [comment]
The only thing I have done is uncomment some of the crontab items in order to do restart, monitor turn off, and every 1 hour refresh the screen.

Beyond that haven't made any modifications the base image

**Comment by SnorreSelmer** [comment]
Try commenting out the monitor on/off stuff and see if that helps. ;)

**Comment by igloo15** [comment]
Right now I have a wireless keyboard dongle in the device which fixes the issue. Even with the keyboard being off as long as that usb dongle is in the pi it correctly goes to webpage instead of raspi-config.

**Comment by jareware** [comment]
I think there was someone else with this issue too, have you tried searching the GitHub issues?

Also please report back if you figure this out!

**Comment by Houzvicka** [comment]
I have the same problem.
The problem is when you call "sudo chvt 1" it didn't do anything.
So, after waking up, switch to terminal two and then to terminal one but that didn't do anything.

**Comment by igloo15** [comment]
Honestly I would not use this image anymore the chromium version is extremely out of date

**Comment by jareware** [comment]
There's now [a new image](https://github.com/jareware/chilipie-kiosk/releases/tag/v3.0.0-rc4) with everything updated to the latest versions.

If you can help test it and report back, it would be much appreciated, and would be happy to mark that as a "stable" release for a change!

**Comment by SnorreSelmer** [comment]
I've tested RC4 a bit, and it seems to work really well. The `display-off/on.sh` turns off my displays and (most importantly) on again without going to the raspi-config console. Haven't tested `cec-off/on.sh` yet as I don't have any HDMI monitors easily available here.

**Comment by jareware** [comment]
Great to hear, thanks!
