### ISSUE TITLE
Google Login fails

### ISSUE THREAD

**Issue by lloydbigoil** [jareware/chilipie-kiosk#152]
I cannot loginto a google account. i am trying to display a dashboard from google sheets but the login fails. Redirects me back to login page. i tried to turn on sync on chromium still cant login.

**Comment by jareware** [comment]
There's now [a new image](https://github.com/jareware/chilipie-kiosk/releases/tag/v3.0.0-rc4) with everything updated to the latest versions.

If you can help test it and report back, it would be much appreciated, and would be happy to mark that as a "stable" release for a change!
