### ISSUE TITLE
chromium needs rng-tools

### ISSUE THREAD

**Issue by mrvanes** [jareware/chilipie-kiosk#49]
Without rng-tools Chromium refuses to start due to a starved random pool entropy (on "headless" pi zero, at least).

**Comment by jareware** [comment]
Interesting, haven't seen this happen!

What do you mean by a "headless" Pi in this instance?

**Comment by mrvanes** [comment]
I actually mean without keyboard or mouse, only touchscreen.

**Comment by jareware** [comment]
OK!

Does it then work if not running headless?

Also, you made me very curious: what's your use case for running `chilipie-kiosk` headless, and on a Zero no less? :)

**Comment by mrvanes** [comment]
I don't know, I never attached a keyboard or mouse. I use it to display HomeAssistant Lovelace webinterface next to my thermostat and use the built-in touchscreen to toggle scenes ;)
The Pi0 is a bit underpowered I admit, but once loaded it reacts fairly well to the touchscreen.

**Comment by jareware** [comment]
Very cool use case!

I'll keep this issue open so I can try to bundle the fix (just `apt-get install rng-tools` worked for you, right?) for the next release, and try it on a Zero.

**Comment by mrvanes** [comment]
Yes, ```apt install rng-tools``` was the solution for getting chromium to start (apt-get is being deprecated).

**Comment by jareware** [comment]
We'll get a regular version-bump release out the door first, and then make a new one with some new features.

Sit tight!

**Comment by ungarida** [comment]
Hi Jarno, thank you for this amazing project, really handy! I have a similar use case. I want to use pi zero because it will be used to show monitoring dashboard on a big screen. Is this still happening?

**Comment by jareware** [comment]
I haven't gotten my hands on a Zero yet for testing, so can't confirm or deny, unfortunately!

Also, while the Zero is seriously cool, I've seen some people get a bit unhappy with how janky it gets when rendering a heavier dashboard. Chromium has to do a lot of work for those, and the Zero can be a bit underpowered for that.

Finally, if someone can confirm that it's just this package that's the fix on a Zero, would be much appreciated!

**Comment by mrvanes** [comment]
As the reporter I surely can confirm that installing rng-tools resolved my problem.
